-- ddp_surgery.sql
-- This script will pull surgery events from the Darwin DCMSPT schema

SELECT
  PTX_PT_DEIDENTIFICATION_ID AS DARWIN_PATIENT_ID,
  DT_DTE AS DATE_OF_PROCEDURE,
  PTX_INPATIENT_OUTPATIENT_IND AS ADMISSION,
  PCC_DESC AS PROCEDURE_DESCRIPTION

FROM PATIENT_PROCEDURE
  JOIN PROCEDURE_CODE_CATALOG
    ON PATIENT_PROCEDURE.PTX_PCC_ID = PROCEDURE_CODE_CATALOG.PCC_ID
  JOIN DATE_V
    ON DT_DATE_ID = PTX_PROC_DATE_ID
WHERE PTX_PROC_SOURCE_DESC = 'OR'
--       AND PTX_PT_DEIDENTIFICATION_ID = 254629
ORDER BY DARWIN_PATIENT_ID, DATE_OF_PROCEDURE;
