-- ddp_interventional_radiology.sql
-- This script will pull IR events from Darwin using the DCMSPT schema
WITH
    IR_TABLE AS (
      SELECT
        RRPT_RPT_ID AS DARWIN_REPORT_ID,
        RRPT_PT_DEIDENTIFICATION_ID AS DARWIN_PATIENT_ID,
        RRPT_ACCESSION_NO AS ACCESSION_NUMBER,
        CASE
          WHEN RRPT_ORDER_GROUP = 'BI IR Breast' THEN 'IR'
          ELSE RRPT_ORDER_GROUP
        END RADIOLOGY_PROCEDURE_ABBV,
        RRPT_PROCEDURE_NAME AS RADIOLOGY_PROCEDURE_DESC,
        RRPT_PERFORMED_DTE AS REPORT_DATE,
        RRPT_ORDER_LOCATION AS ORDER_LOCATION,
        RRPT_DEID_RPT_TXT AS REPORT_TXT_DEID,
        RRPT_ORDER_GROUP

      FROM RADIOLOGY_REPORT_V
     WHERE RRPT_ORDER_GROUP = 'IR'
  )

SELECT *
  FROM IR_TABLE;
-- WHERE DARWIN_PATIENT_ID = 254629;